"""Updated CourseRating

Revision ID: 2b6bdb05c181
Revises: 3492b5bd53f
Create Date: 2013-03-02 15:07:18.394982

"""

# revision identifiers, used by Alembic.
revision = '2b6bdb05c181'
down_revision = '3492b5bd53f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_rating', sa.Column('is_accepted', sa.Boolean(), nullable=True))
    op.add_column('course_rating', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('course_rating', sa.Column('posted_on', sa.DateTime(), nullable=True))
    op.drop_column('course_rating', u'student_promotion')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_rating', sa.Column(u'student_promotion', mysql.INTEGER(display_width=11), nullable=True))
    op.drop_column('course_rating', 'posted_on')
    op.drop_column('course_rating', 'is_verified')
    op.drop_column('course_rating', 'is_accepted')
    ### end Alembic commands ###
