"""initial

Revision ID: 3492b5bd53f
Revises: None
Create Date: 2013-02-19 22:29:34.763206

"""

# revision identifiers, used by Alembic.
revision = '3492b5bd53f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('teacher_name', sa.String(length=60), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('course_rating',
    sa.Column('course_rating_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_email', sa.String(length=60), nullable=True),
    sa.Column('student_promotion', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('course_rating_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_rating')
    op.drop_table('course')
    ### end Alembic commands ###
